# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c2ac71b0d4cd9f3ea0137b8d74919a7fac7f80b9af1ee60a87238216ff77d1e3f5c7ff24c9eb12e825608621e0d936b99dbc2f6022845e857190f74b2cb7281

test:
  secret_key_base: 28c86ac408af51c5c1958c7f7f5f20e5d713c17a6cd871d02596c1576f55b0626902a7974a20a7933a9cd7c54041a4ebd6b0d193a5255cc0d40ffa48302b6025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
